#!/bin/zsh

if [[ "$XDG_SESSION_DESKTOP" == "awesome" ]]; then
  export PATH="$HOME/bin:$PATH"

  # Setup the input bus for CJK input
  export GTK_IM_MODULE=fcitx
  export XMODIFIERS=@im=fcitx
  export QT_IM_MODULE=fcitx

  # Turn off screen blanking
  xset -dpms s off s noblank

  # Enable PA systray control
  pasystray &

  # Enable FCITX
  fcitx &

  # Enable XScreensaver
  xscreensaver -no-splash &

  # Enable window compositing
  xcompmgr -Cc -r0 -o0 -l0 -t0  &
fi
